package random.nist;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/** Compares the first Java ports with p-values generated by NIST STS 2.1.2 for data.pi. */
public final class NistReferenceVerification {
    private static final int STREAM_LENGTH = 100_000;
    private static final double REFERENCE_ROUNDING_TOLERANCE = 0.0000006;
    private static final double[] FREQUENCY = {
            0.617329, 0.869386, 0.179984, 0.031031, 0.531229,
            0.293775, 0.215119, 0.208180, 0.590862, 0.934472
    };
    private static final double[] RUNS = {
            0.174149, 0.502546, 0.704806, 0.128505, 0.241483,
            0.107552, 0.109244, 0.342105, 0.915103, 0.535399
    };
    private static final double[] BLOCK_FREQUENCY = {
            0.557590, 0.438757, 0.436896, 0.602399, 0.808519,
            0.149256, 0.011606, 0.207561, 0.556649, 0.119626
    };
    private static final double[] CUMULATIVE_SUMS = {
            0.395930, 0.762666, 0.739026, 0.587086, 0.120655, 0.140957, 0.037272, 0.057758,
            0.847797, 0.667864, 0.427516, 0.337823, 0.391556, 0.174238, 0.276074, 0.409259,
            0.730124, 0.718241, 0.911729, 0.847797
    };
    private static final double[] LONGEST_RUN = {
            0.948239, 0.352573, 0.898224, 0.616268, 0.743759,
            0.158815, 0.394693, 0.462595, 0.376291, 0.314735
    };
    private static final double[] APPROXIMATE_ENTROPY = {
            0.607834, 0.604391, 0.889162, 0.576346, 0.217775,
            0.194184, 0.757763, 0.367337, 0.686607, 0.369223
    };
    private static final double[] SERIAL = {
            0.865190, 0.326983, 0.001995, 0.009405, 0.081462, 0.190732, 0.317172, 0.276749,
            0.977913, 0.982682, 0.642963, 0.588146, 0.228568, 0.597997, 0.220169, 0.086354,
            0.980500, 0.971128, 0.099223, 0.130298
    };
    private static final double[] RANK = {
            0.625635, 0.356565, 0.908912, 0.645643, 0.973521,
            0.076568, 0.100317, 0.579982, 0.785821, 0.440798
    };
    private static final double[] LINEAR_COMPLEXITY = {
            0.028114, 0.877211, 0.656262, 0.088433, 0.221074,
            0.584383, 0.172407, 0.855778, 0.938071, 0.135151
    };
    private static final double[] OVERLAPPING_TEMPLATE = {
            0.996425, 0.561707, 0.001097, 0.289210, 0.328182,
            0.064333, 0.026942, 0.042433, 0.326178, 0.931102
    };
    private static final double[] FFT = {
            0.081659, 0.884636, 0.110478, 0.468160, 0.523201,
            0.749568, 0.017333, 0.486143, 0.684547, 0.816420
    };

    private NistReferenceVerification() {
    }

    public static void main(String[] args) throws Exception {
        if (args.length < 1 || args.length > 2) {
            throw new IllegalArgumentException("Expected the path to data.pi and optionally 'universal'.");
        }

        Path dataPath = Path.of(args[0]);
        BitSequence input = BitSequence.fromAsciiFile(dataPath);
        if (args.length == 2 && args[1].equalsIgnoreCase("universal")) {
            BitSequence millionBits = input.slice(0, 1_000_000);
            double actual = new UniversalStatisticalTest().test(millionBits, 0.01).pValue();
            verify("Universal Statistical", 0, actual, 0.669012);
            System.out.println("NIST Java parity verified for Universal Statistical on 1,000,000 data.pi bits.");
            return;
        }
        Path resultRoot = dataPath.getParent().getParent().resolve("experiments/AlgorithmTesting");
        double[] nonOverlappingExpected = readResults(resultRoot.resolve("NonOverlappingTemplate/results.txt"));
        double[] excursionsExpected = readResults(resultRoot.resolve("RandomExcursions/results.txt"));
        double[] variantExpected = readResults(resultRoot.resolve("RandomExcursionsVariant/results.txt"));
        NistRandomnessTest frequency = new FrequencyMonobitTest();
        NistRandomnessTest runs = new RunsTest();
        NistRandomnessTest blockFrequency = new BlockFrequencyTest(128);
        NistRandomnessTest cumulativeSums = new CumulativeSumsTest();
        NistRandomnessTest longestRun = new LongestRunOfOnesTest();
        NistRandomnessTest approximateEntropy = new ApproximateEntropyTest(10);
        NistRandomnessTest serial = new SerialTest(16);
        NistRandomnessTest rank = new BinaryMatrixRankTest();
        NistRandomnessTest linearComplexity = new LinearComplexityTest(500);
        NistRandomnessTest overlappingTemplate = new OverlappingTemplateTest(9);
        NistRandomnessTest fft = new DiscreteFourierTransformTest();
        NistRandomnessTest nonOverlappingTemplate = new NonOverlappingTemplateTest(9);
        NistRandomnessTest excursions = new RandomExcursionsTest();
        NistRandomnessTest excursionsVariant = new RandomExcursionsVariantTest();
        for (int stream = 0; stream < FREQUENCY.length; stream++) {
            BitSequence sequence = input.slice(stream * STREAM_LENGTH, (stream + 1) * STREAM_LENGTH);
            verify("Frequency", stream, frequency.test(sequence, 0.01).pValue(), FREQUENCY[stream]);
            verify("Runs", stream, runs.test(sequence, 0.01).pValue(), RUNS[stream]);
            verify("Block Frequency", stream, blockFrequency.test(sequence, 0.01).pValue(), BLOCK_FREQUENCY[stream]);
            verify("Longest Run", stream, longestRun.test(sequence, 0.01).pValue(), LONGEST_RUN[stream]);
            verify("Approximate Entropy", stream, approximateEntropy.test(sequence, 0.01).pValue(),
                    APPROXIMATE_ENTROPY[stream]);
            verifyAll("Cumulative Sums", stream, cumulativeSums.testAll(sequence, 0.01), CUMULATIVE_SUMS);
            verifyAll("Serial", stream, serial.testAll(sequence, 0.01), SERIAL);
            verify("Rank", stream, rank.test(sequence, 0.01).pValue(), RANK[stream]);
            verify("Linear Complexity", stream, linearComplexity.test(sequence, 0.01).pValue(),
                    LINEAR_COMPLEXITY[stream]);
            verify("Overlapping Template", stream, overlappingTemplate.test(sequence, 0.01).pValue(),
                    OVERLAPPING_TEMPLATE[stream]);
            verify("FFT", stream, fft.test(sequence, 0.01).pValue(), FFT[stream]);
            verifyAll("Non-overlapping Template", stream, nonOverlappingTemplate.testAll(sequence, 0.01),
                    nonOverlappingExpected);
            verifyAll("Random Excursions", stream, excursions.testAll(sequence, 0.01), excursionsExpected);
            verifyAll("Random Excursions Variant", stream, excursionsVariant.testAll(sequence, 0.01),
                    variantExpected);
        }
        System.out.println("NIST Java parity verified for 14 test categories across 10 data.pi streams.");
    }

    private static void verifyAll(
            String test,
            int stream,
            List<NistTestResult> results,
            double[] expected
    ) {
        for (int result = 0; result < results.size(); result++) {
            verify(test + " result " + result, stream, results.get(result).pValue(),
                    expected[stream * results.size() + result]);
        }
    }

    private static void verify(String test, int stream, double actual, double expected) {
        double difference = Math.abs(actual - expected);
        if (difference > REFERENCE_ROUNDING_TOLERANCE) {
            throw new AssertionError(test + " stream " + stream + ": expected " + expected
                    + ", actual " + actual + ", difference " + difference);
        }
    }

    private static double[] readResults(Path path) throws Exception {
        try (var lines = Files.lines(path)) {
            return lines.filter(line -> !line.isBlank()).mapToDouble(Double::parseDouble).toArray();
        }
    }
}
